env:
  - CGO_ENABLED=0

before:
  hooks:
    - make test
    - go mod tidy
    - go mod download

builds:
  - id: traefik-acme
    main: ./cmd/traefik-acme
    binary: traefik-acme
    targets:
      - linux_amd64
      - darwin_amd64

checksum:
  algorithm: sha256
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  -
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    binaries:
    - traefik-acme
    builds:
    - traefik-acme
    skip_push: true
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    image_templates:
    - "koshatul/traefik-acme:v{{ .Major }}"
    - "koshatul/traefik-acme:v{{ .Major }}.{{ .Minor }}"
    - "koshatul/traefik-acme:latest"

nfpms:
  -
    id: traefik-acme
    package_name: traefik-acme
    file_name_template: "traefik-acme_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - traefik-acme
    homepage: https://github.com/koshatul/traefik-acme
    maintainer: koshatul <koshatul@users.noreply.github.com>
    description: Traefik ACME extraction tool.
    formats:
      - apk
      - deb
    bindir: /usr/bin

