env:
  - CGO_ENABLED=0

before:
  hooks:
    - make test
    - go mod tidy
    - go mod download

builds:
  - id: traefik-acme
    main: ./cmd/traefik-acme
    binary: traefik-acme
    targets:
      - linux_amd64
      - darwin_amd64
      - linux_arm_5
      - linux_arm_7
      - linux_arm64

checksum:
  algorithm: sha256
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  -
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    binaries:
    - traefik-acme
    builds:
    - traefik-acme
    build_flag_templates:
    - "--build-arg=PLATFORM=linux/amd64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    image_templates:
    - "koshatul/traefik-acme:latest-amd64"
    - "koshatul/traefik-acme:v{{ .Major }}-amd64"
    - "koshatul/traefik-acme:v{{ .Major }}.{{ .Minor }}-amd64"
  -
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    binaries:
    - traefik-acme
    builds:
    - traefik-acme
    build_flag_templates:
    - "--build-arg=PLATFORM=linux/arm64/v8"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    image_templates:
    - "koshatul/traefik-acme:latest-arm64v8"
    - "koshatul/traefik-acme:v{{ .Major }}-arm64v8"
    - "koshatul/traefik-acme:v{{ .Major }}.{{ .Minor }}-arm64v8"
  -
    goos: linux
    goarch: arm
    goarm: 7
    dockerfile: Dockerfile.goreleaser
    binaries:
    - traefik-acme
    builds:
    - traefik-acme
    build_flag_templates:
    - "--build-arg=PLATFORM=linux/arm/v7"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    image_templates:
    - "koshatul/traefik-acme:latest-armv7"
    - "koshatul/traefik-acme:v{{ .Major }}-armv7"
    - "koshatul/traefik-acme:v{{ .Major }}.{{ .Minor }}-armv7"

docker_manifests:
  - name_template: koshatul/traefik-acme:v{{ .Major }}
    image_templates:
    - koshatul/traefik-acme:v{{ .Major }}-amd64
    - koshatul/traefik-acme:v{{ .Major }}-armv7
    - koshatul/traefik-acme:v{{ .Major }}-arm64v8
  - name_template: koshatul/traefik-acme:v{{ .Major }}.{{ .Minor }}
    image_templates:
    - koshatul/traefik-acme:v{{ .Major }}.{{ .Minor }}-amd64
    - koshatul/traefik-acme:v{{ .Major }}.{{ .Minor }}-armv7
    - koshatul/traefik-acme:v{{ .Major }}.{{ .Minor }}-arm64v8
  - name_template: koshatul/traefik-acme:latest
    image_templates:
    - koshatul/traefik-acme:latest-amd64
    - koshatul/traefik-acme:latest-armv7
    - koshatul/traefik-acme:latest-arm64v8

nfpms:
  -
    id: traefik-acme
    package_name: traefik-acme
    builds:
      - traefik-acme
    homepage: https://github.com/koshatul/traefik-acme
    maintainer: koshatul <koshatul@users.noreply.github.com>
    description: Traefik ACME extraction tool.
    formats:
      - apk
      - deb
    bindir: /usr/bin

