name: ci

on:
  pull_request:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go
      - name: Set up go env
        run: export PATH=${PATH}:`go env GOPATH`/bin
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32

  unit-test:
    name: unit-test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go
      - name: Set up go env
        run: export PATH=${PATH}:`go env GOPATH`/bin
      - name: unit-test
        run: make test
      - name: ci
        run: make ci

  goreleaser:
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - unit-test
      - golangci
    name: goreleaser
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Docker registry login
        run: ./scripts/docker-login.sh
        env:
          INPUT_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          INPUT_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go
      - name: Set up go env
        run: export PATH=${PATH}:`go env GOPATH`/bin
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: 20.04
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}