name: ci

on:
  pull_request:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go
      - name: Set up go env
        run: export PATH=${PATH}:`go env GOPATH`/bin
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.33

  unit-test:
    name: unit-test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go
      - name: Set up go env
        run: export PATH=${PATH}:`go env GOPATH`/bin
      - name: unit-test
        run: make test
      - name: ci
        run: make ci

  goreleaser:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - unit-test
      - golangci
    name: goreleaser
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Enable experimental features for the Docker daemon and CLI
        run: |
          echo $'{"experimental":true,"features":{"buildkit":true}}' | sudo tee /etc/docker/daemon.json
          mkdir -p ~/.docker
          echo $'{"experimental": "enabled","features":{"buildkit":true}}' | sudo tee ~/.docker/config.json
          sudo service docker restart
          docker version
          docker buildx version
          docker buildx ls
      - name: Docker registry login
        run: ./scripts/docker-login.sh
        env:
          INPUT_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          INPUT_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go
      - name: Set up go env
        run: export PATH=${PATH}:`go env GOPATH`/bin
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}