name: ci

on:
  pull_request:
  push:
    branches:
    - '*'
    tags:
    - '*'

jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1
      id: go

    - name: Set up go env
      run: export PATH=${PATH}:`go env GOPATH`/bin

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3.1.0
      with:
        version: latest

    - name: unit-test
      run: make test

    - name: ci
      run: make ci

  goreleaser:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
    - unit-test
    name: goreleaser
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Docker registry login
      run: ./scripts/docker-login.sh
      env:
        INPUT_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        INPUT_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1
      id: go

    - name: Set up go env
      run: export PATH=${PATH}:`go env GOPATH`/bin

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
